AllCops:
  Excludes:
    - benchmarks/**/*

StringLiterals:
  EnforcedStyle: double_quotes
SignalException:
  Enabled: false
CollectionMethods:
  PreferredMethods:
    collect: map
    collect!: map!
    reduce: inject
    detect: find
    find_all: select
ReduceArguments:
  Enabled: false
OneLineConditional:
  Enabled: false
